name: GitHub Metrics
on:
  # Roda a cada 24h automaticamente
  schedule: [{cron: "0 0 * * *"}]
  # Permite rodar manualmente
  workflow_dispatch:
  # Roda sempre que houver um push na main
  push: {branches: ["main", "master"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # O Token precisa ser criado com as permissões 'repo' e 'read:org'
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Arquivo gerado
          filename: github-metrics-languages.svg
          
          # Tema para combinar com o seu dracula
          theme: dracula
          
          # Desabilita estatísticas base para focar nas linguagens
          base: ""
          
          # Plugin de Linguagens
          plugin_languages: yes
          plugin_languages_ignored: html, css, scss
          plugin_languages_limit: 8
          plugin_languages_details: percentage
          
          # IN-DEPTH: É ISSO QUE RESOLVE O PROBLEMA DAS ORGANIZAÇÕES!
          plugin_languages_indepth: yes
          # Aumentamos os limites ao MÁXIMO para forçar a leitura do seu histórico antigo (onde está o PHP)
          plugin_languages_analysis_timeout: 300
          plugin_languages_recent_days: 0
          plugin_languages_recent_load: 2000
          plugin_languages_categories: programming
          
          # Estilização CSS para forçar o fundo do Dracula e deixar parecido com os outros cards
          extras_css: |
            svg { background-color: #282a36 !important; border-radius: 10px !important; }
            h2, h3 { color: #bd93f9 !important; }
            .field, .field svg { color: #f8f8f2 !important; fill: #f8f8f2 !important; }
            .language.details small { color: #6272a4 !important; }
